export type UpdateStatus = 'minor' | 'moderate' | 'major'
export type UpdateCategory = 'update' | 'fixing' | 'refactor' | 'revamp'

export interface UpdateEntry {
  date: string
  title: string
  status: UpdateStatus
  type: UpdateCategory
  version: string
  description: string
}

export const WEB_UPDATE_LOG: UpdateEntry[] = [
  {
    date: '11 August 2026',
    title: 'Local Weather Forecast V3.3 — Four Independent Neural Networks',
    status: 'moderate',
    type: 'update',
    version: '1.20.0',
    description: 'V3.3 experiment: 4 independent NNs (one per slot) with own embeddings. Tests slot specialization vs shared representation. Result: no improvement over V3 shared architecture (~64% F1, 242 KB).',
  },
  {
    date: '11 August 2026',
    title: 'Local Weather Forecast V3.1 — Capacity & Regularization Experiment',
    status: 'moderate',
    type: 'update',
    version: '1.19.0',
    description: 'V3.1 experiment: larger network [128,64,32] + embedding dim 16. Includes dropout + weight decay test. Result: no meaningful improvement — confirms data/feature bottleneck, not model capacity.',
  },
  {
    date: '11 August 2026',
    title: 'Local Weather Forecast V3 — First Neural Network (Shared MLP)',
    status: 'moderate',
    type: 'update',
    version: '1.18.0',
    description: 'New AI module: Shared MLP with location embedding (dim=8) + cyclical temporal encoding. 64 KB model, Macro F1 64.16% — beats V2.5 (63.1%) at 5× smaller size. Pure TS training pipeline.',
  },
  {
    date: '21 July 2026',
    title: 'Device compatibility badges on playground module cards',
    status: 'minor',
    type: 'update',
    version: '1.17.1',
    description: 'Each module card now shows Desktop and Mobile compatibility badges (smooth/limited/unsupported) with hover tooltips. Defined as required field in moduleRegistry. AI Upscaler disclaimer updated with performance lag warning.',
  },
  {
    date: '18 July 2026',
    title: 'Advanced Image Upscaler — Real-ESRGAN via LiteRT.js',
    status: 'moderate',
    type: 'update',
    version: '1.17.0',
    description: 'New AI module: Real-ESRGAN x4v3 (4.1 MB TFLite) via LiteRT.js. Overlapping-tile inference (stride 96px, 16px overlap) for seam-free output. Download consent flow — no auto-download. WebGPU/WASM fallback. Per-tile progress. CPU warning. Slider comparison.',
  },
  {
    date: '18 July 2026',
    title: 'Quick Image Upscaler — multi-algorithm WebGPU upscaling tool',
    status: 'moderate',
    type: 'update',
    version: '1.16.0',
    description: 'New Tool module: Quick Image Upscaler. 4 algorithms — Bicubic, Lanczos3, FSR1 (fixed), Jinc EWA. WebGPU explicit availability, no silent fallback. Slider comparison. Realtime params. All playground copy centralized.',
  },
  {
    date: '30 June 2026',
    title: 'Tic Tac Toe: single-column layout, brighter board cells, primary reset button',
    status: 'minor',
    type: 'update',
    version: '1.15.1',
    description: 'Layout changed to single centered column for all screens. How to Play box removed. Board cells use border-white/20 for better visibility. Reset button changed to btn-angular-primary.',
  },
  {
    date: '30 June 2026',
    title: 'Tic Tac Toe module — PvP and PvC with three bot difficulty levels',
    status: 'moderate',
    type: 'update',
    version: '1.15.0',
    description: 'New Game module: Tic Tac Toe. PvP mode for two players on one device. PvC mode pits you against a bot at Easy (random), Medium (win/block/random), or Hard (unbeatable Minimax). Confirm modals guard mode changes, difficulty changes, and resets while a game is in progress.',
  },
  {
    date: '30 June 2026',
    title: 'Story localization toggle, footer copy sync, navbar version',
    status: 'minor',
    type: 'update',
    version: '1.14.8',
    description: 'Story detail shows EN/ID toggle when Indonesian content exists. Footer subtitle synced from HOME_COPY. Navbar shows app version. GraphQL raw field removed.',
  },
  {
    date: '28 June 2026',
    title: 'Navbar version badge, weather about copy centralized',
    status: 'minor',
    type: 'update',
    version: '1.14.7',
    description: 'App version shown in navbar next to logo. Weather V1/V2/V2.5 about sections moved to centralized copy with accuracy & F1 scores.',
  },
  {
    date: '28 June 2026',
    title: 'Split Bill: colorful detail page with icons and person avatars',
    status: 'minor',
    type: 'update',
    version: '1.14.6',
    description: 'Bill detail page redesigned with colored meta cards, person icon avatars, item tag icons, and paid/unpaid visual states. Avatars also applied to create/edit form.',
  },
  {
    date: '26 June 2026',
    title: 'Split Bill: single chunk loading via Vite manualChunks',
    status: 'minor',
    type: 'refactor',
    version: '1.14.5',
    description: 'All split-bill routes and components bundled into one chunk. Opening the module loads everything at once — no extra requests for sub-pages.',
  },
  {
    date: '26 June 2026',
    title: 'Hero carousel: Split Bill slide, intro CTA scroll, remove config file',
    status: 'minor',
    type: 'refactor',
    version: '1.14.4',
    description: 'Added Split Bill slide to hero carousel (now 5 slides). Intro CTA scrolls to Featured section instead of navigating. Removed heroCarouselConfig.ts. Updated hero subtitle & CTA copy.',
  },
  {
    date: '25 June 2026',
    title: 'Split Bill: fix QR cross-device decrypt, import always visible',
    status: 'minor',
    type: 'fixing',
    version: '1.14.3',
    description: 'QR now uses shared key from env (not per-device DEK). Import QR button visible even with empty bill list. PIN state does not affect QR compatibility.',
  },
  {
    date: '25 June 2026',
    title: 'Split Bill: QR sharing (generate, scan, import)',
    status: 'minor',
    type: 'update',
    version: '1.14.2',
    description: 'Share bills via encrypted QR code. Scan from camera or import image. Confirm step with editable title before saving imported bill.',
  },
  {
    date: '25 June 2026',
    title: 'Split Bill: full encryption (title + participant names) & bill search',
    status: 'minor',
    type: 'update',
    version: '1.14.1',
    description: 'Bill title and participant names now encrypted in IndexedDB. Added bill search on home. Removed summary text from bill list for privacy.',
  },
  {
    date: '25 June 2026',
    title: 'Split Bill module — offline encrypted bill splitting with PIN protection',
    status: 'moderate',
    type: 'update',
    version: '1.14.0',
    description: 'New playground module: split bills (equal/custom/itemized), encrypted IndexedDB with DEK+KEK, optional PIN lock, global reusable participants.',
  },
  {
    date: '24 June 2026',
    title: 'PWA selective asset download: seamless offline preservation across deploys',
    status: 'moderate',
    type: 'update',
    version: '1.13.0',
    description: 'SW re-fetches HTML + JS/CSS for visited pages on update. Auto-activate when app relaunched, prompt only if user active. Offline works seamlessly after deploy.',
  },
  {
    date: '23 June 2026',
    title: 'PWA offline redesign: prompt-based updates, selective asset download, Workbox',
    status: 'major',
    type: 'revamp',
    version: '1.12.0',
    description: 'New SW with route-manifest mapping, selective chunk download for visited routes only, staging cache, UpdatePrompt UI, and Workbox caching strategies.',
  },
  {
    date: '23 June 2026',
    title: 'Cleaning "V3" copywriting in some file',
    status: 'minor',
    type: 'fixing',
    version: '1.11.3',
    description: 'Cleaning "V3" copywriting in some file',
  },
  {
    date: '23 June 2026',
    title: 'Weather modules UI polish: label colors, toggle redesign',
    status: 'minor',
    type: 'fixing',
    version: '1.11.2',
    description: 'Input labels changed to white for visibility. Standard/Sensitive toggle redesigned as orange pill toggle. How to Use updated with mode explanation.',
  },
  {
    date: '23 June 2026',
    title: 'Local Weather Forecast V2.5 — Gradient Boosted Trees with computed features',
    status: 'moderate',
    type: 'update',
    version: '1.11.1',
    description: 'New module: GBT (100 trees × depth 4) per slot with sin/cos day, day length features. Better F1 via probability calibration + threshold tuning.',
  },
  {
    date: '23 June 2026',
    title: 'Weather V2 & V2.5: Standard/Sensitive prediction mode toggle',
    status: 'minor',
    type: 'update',
    version: '1.11.0',
    description: 'Added prediction mode toggle. Standard: threshold 0.5, higher accuracy. Sensitive: tuned thresholds, better rain detection (higher F1).',
  },
  {
    date: '23 June 2026',
    title: 'Fix __APP_VERSION__ ReferenceError in SSR context',
    status: 'minor',
    type: 'fixing',
    version: '1.10.1',
    description: 'Added typeof guard for __APP_VERSION__ in HeroSection and Footer to prevent crash when Vite define is unavailable during SSR.',
  },
  {
    date: '22 June 2026',
    title: 'Local Weather Forecast V2 — per-slot rain prediction with prevDay feature',
    status: 'moderate',
    type: 'update',
    version: '1.10.0',
    description: 'New module: 4 independent Random Forests predict rain/no-rain per time slot (Pagi/Siang/Sore/Malam). Added prevDayRainSlots feature. 73% avg accuracy.',
  },
  {
    date: '21 June 2026',
    title: 'Swap info box order in Weather module, Tool label color to yellow',
    status: 'minor',
    type: 'fixing',
    version: '1.9.1',
    description: '"How to Use" now appears before "About" in Weather module. Playground Tool label color changed from orange to yellow for better distinction.',
  },
  {
    date: '21 June 2026',
    title: 'Home revamp (Hero carousel, API Featured), About restructure, /log merged, reusable Carousel',
    status: 'moderate',
    type: 'revamp',
    version: '1.9.0',
    description: 'Hero carousel (4 slides, auto-scroll 10s). Featured uses Hygraph API. CTA → Playground. /log merged into About with infinite scroll. Reusable Carousel component.',
  },
  {
    date: '21 June 2026',
    title: 'Switch offline badge to Cache API, remove localStorage dependency',
    status: 'minor',
    type: 'fixing',
    version: '1.8.1',
    description: 'Offline status now uses Cache API as single source of truth. Removed localStorage tracking for more accurate offline detection.',
  },
  {
    date: '21 June 2026',
    title: 'Playground per-module routing, offline status badge, search & NotFoundPage refactor',
    status: 'moderate',
    type: 'refactor',
    version: '1.8.0',
    description: 'Modules now have dedicated routes (/playground/<id>). Removed load() from manifest. Added offline badge, search, and reusable NotFoundPage.',
  },
  {
    date: '20 June 2026',
    title: 'Local Weather Forecast module — offline rain prediction',
    status: 'moderate',
    type: 'update',
    version: '1.7.0',
    description: 'AI module: Random Forest (40 trees, depth 6) prediksi hujan 514 kota Indonesia. Offline inference <1ms di browser.',
  },
  {
    date: '20 June 2026',
    title: 'Playground route & module system',
    status: 'moderate',
    type: 'update',
    version: '1.6.0',
    description: 'New /playground route with dynamic module loading, lifecycle management, label badges (AI/Tool/Game), and searchable UI.',
  },
  {
    date: '19 June 2026',
    title: 'PWA offline overhaul & navbar diamond marker fix',
    status: 'moderate',
    type: 'update',
    version: '1.5.1',
    description: 'Revamped service worker with layered offline fallback, split caches, and precaching of main routes. Fixed diamond marker alignment on mobile.',
  },
  {
    date: '5 June 2026',
    title: 'Dual-tone accent (purple & orange) + SectionHeader component',
    status: 'moderate',
    type: 'revamp',
    version: '1.5.0',
    description: 'Switched accent to dual-tone purple + orange. Created reusable SectionHeader. Renamed PWA icons to feldora-logo PNG format.',
  },
  {
    date: '4 June 2026',
    title: 'New icon',
    status: 'minor',
    type: 'revamp',
    version: '1.4.1',
    description: 'Replaced webp logo with proper PNG icons (192x192 and 512x512) for PWA manifest and browser favicon compatibility.',
  },
  {
    date: '4 June 2026',
    title: 'Infinite scroll on StoryList & Spinner component',
    status: 'moderate',
    type: 'update',
    version: '1.4.0',
    description: 'Infinite scroll via useInfiniteQuery + IntersectionObserver. Paginated Hygraph query (12/page). Added Spinner and mock API.',
  },
  {
    date: '4 June 2026',
    title: 'Centralize copywriting to dedicated directory',
    status: 'minor',
    type: 'refactor',
    version: '1.3.2',
    description: 'Moved all hardcoded text into src/constants/copy/ per page. Components now import from centralized copy files.',
  },
  {
    date: '4 June 2026',
    title: 'Fixing UI & Refactor Code',
    status: 'minor',
    type: 'fixing',
    version: '1.3.1',
    description: 'Extracted StoryCard as shared component. Fixed mobile scroll on log page. Created PageHeader and NotFoundPage components.',
  },
  {
    date: '4 June 2026',
    title: 'Error & Loading State handling',
    status: 'moderate',
    type: 'update',
    version: '1.3.0',
    description: 'GlobalLoader, Skeleton components, ErrorState, ErrorPage boundary, OfflineBanner, and Toast notification system.',
  },
  {
    date: '4 June 2026',
    title: 'Implement PWA with offline support',
    status: 'moderate',
    type: 'update',
    version: '1.2.0',
    description: 'Added manifest.json, service worker with network-first caching, offline.html fallback. App now installable on mobile and desktop.',
  },
  {
    date: '4 June 2026',
    title: 'Revamp Update Log system & add LogCard component',
    status: 'moderate',
    type: 'revamp',
    version: '1.1.0',
    description: 'Restructured log data with status/type/version fields. Created LogCard with accordion, color-coded badges, and hover tooltips.',
  },
  {
    date: '2 June 2026',
    title: 'Complete rebuild with TanStack Start + TypeScript + cinematic design system',
    status: 'major',
    type: 'refactor',
    version: '1.0.0',
    description: 'Full migration to TanStack Start + SSR + Nitro. Cinematic dark design system inspired by Riot Games. TypeScript strict mode.',
  },
  {
    date: '18 September 2025',
    title: 'Installing new fonts + change update log data to constant',
    status: 'minor',
    type: 'update',
    version: '0.4.3',
    description: 'Added custom fonts (Inter, JetBrains Mono) and migrated update log data to a dedicated constants file.',
  },
  {
    date: '9 Februari 2025',
    title: 'Update post-body-content',
    status: 'minor',
    type: 'update',
    version: '0.4.2',
    description: 'Updated post page formatting.',
  },
  {
    date: '9 Februari 2025',
    title: 'Fixing Loading and Vercel go-to-specific-routes bug',
    status: 'minor',
    type: 'fixing',
    version: '0.4.1',
    description: 'Fixed Vercel configuration for direct route navigation.',
  },
  {
    date: '8 Februari 2025',
    title: 'Fixing post page layout, body-content-HTML, and post card',
    status: 'moderate',
    type: 'fixing',
    version: '0.4.0',
    description: 'Fixed post page format to match rich-text-editor data output.',
  },
  {
    date: '8 Februari 2025',
    title: 'Add Update log & Implement React-helmet',
    status: 'moderate',
    type: 'update',
    version: '0.3.0',
    description: 'Added log page for tracking website updates. Implemented react-helmet for async page titles.',
  },
  {
    date: '8 Februari 2025',
    title: 'Revamp UI, styling, and layout. Add new webLogo & page animation',
    status: 'minor',
    type: 'refactor',
    version: '0.2.1',
    description: 'Revamped UI & layout. Added new Feldora logo and page transition animations.',
  },
  {
    date: '2 Agustus 2024',
    title: 'Implement GetPost and post page using React Query and GraphQL',
    status: 'moderate',
    type: 'update',
    version: '0.2.0',
    description: 'Integrated React Query with Hygraph GraphQL API for post fetching.',
  },
  {
    date: '22 Juli 2024',
    title: 'Initialize React Query',
    status: 'moderate',
    type: 'update',
    version: '0.1.0',
    description: 'Installed and configured React Query. Set development rules & standards.',
  },
  {
    date: '9 Juli 2024',
    title: 'Initialize Project',
    status: 'major',
    type: 'update',
    version: '0.0.0',
    description: 'Initialized Feldora with Vite + React. Planned react-query for data fetching & state management.',
  },
]
