export type UpdateStatus = 'minor' | 'moderate' | 'major'
export type UpdateCategory = 'update' | 'fixing' | 'refactor' | 'revamp'

export interface UpdateEntry {
  date: string
  title: string
  status: UpdateStatus
  type: UpdateCategory
  version: string
  description: string
}

export const WEB_UPDATE_LOG: UpdateEntry[] = [
  {
    date: '21 June 2026',
    title: 'Switch offline badge to Cache API, remove localStorage dependency',
    status: 'minor',
    type: 'fixing',
    version: '1.8.1',
    description: 'Offline status now uses Cache API as single source of truth. Removed localStorage tracking for more accurate offline detection.',
  },
  {
    date: '21 June 2026',
    title: 'Playground per-module routing, offline status badge, search & NotFoundPage refactor',
    status: 'moderate',
    type: 'refactor',
    version: '1.8.0',
    description: 'Modules now have dedicated routes (/playground/<id>). Removed load() from manifest. Added offline badge, search, and reusable NotFoundPage.',
  },
  {
    date: '20 June 2026',
    title: 'Local Weather Forecast module — offline rain prediction',
    status: 'moderate',
    type: 'update',
    version: '1.7.0',
    description: 'AI module: Random Forest (40 trees, depth 6) prediksi hujan 514 kota Indonesia. Offline inference <1ms di browser.',
  },
  {
    date: '20 June 2026',
    title: 'Playground route & module system',
    status: 'moderate',
    type: 'update',
    version: '1.6.0',
    description: 'New /playground route with dynamic module loading, lifecycle management, label badges (AI/Tool/Game), and searchable UI.',
  },
  {
    date: '19 June 2026',
    title: 'PWA offline overhaul & navbar diamond marker fix',
    status: 'moderate',
    type: 'update',
    version: '1.5.1',
    description: 'Revamped service worker with layered offline fallback, split caches, and precaching of main routes. Fixed diamond marker alignment on mobile.',
  },
  {
    date: '5 June 2026',
    title: 'Dual-tone accent (purple & orange) + SectionHeader component',
    status: 'moderate',
    type: 'revamp',
    version: '1.5.0',
    description: 'Switched accent to dual-tone purple + orange. Created reusable SectionHeader. Renamed PWA icons to feldora-logo PNG format.',
  },
  {
    date: '4 June 2026',
    title: 'New icon',
    status: 'minor',
    type: 'revamp',
    version: '1.4.1',
    description: 'Replaced webp logo with proper PNG icons (192x192 and 512x512) for PWA manifest and browser favicon compatibility.',
  },
  {
    date: '4 June 2026',
    title: 'Infinite scroll on StoryList & Spinner component',
    status: 'moderate',
    type: 'update',
    version: '1.4.0',
    description: 'Infinite scroll via useInfiniteQuery + IntersectionObserver. Paginated Hygraph query (12/page). Added Spinner and mock API.',
  },
  {
    date: '4 June 2026',
    title: 'Centralize copywriting to dedicated directory',
    status: 'minor',
    type: 'refactor',
    version: '1.3.2',
    description: 'Moved all hardcoded text into src/constants/copy/ per page. Components now import from centralized copy files.',
  },
  {
    date: '4 June 2026',
    title: 'Fixing UI & Refactor Code',
    status: 'minor',
    type: 'fixing',
    version: '1.3.1',
    description: 'Extracted StoryCard as shared component. Fixed mobile scroll on log page. Created PageHeader and NotFoundPage components.',
  },
  {
    date: '4 June 2026',
    title: 'Error & Loading State handling',
    status: 'moderate',
    type: 'update',
    version: '1.3.0',
    description: 'GlobalLoader, Skeleton components, ErrorState, ErrorPage boundary, OfflineBanner, and Toast notification system.',
  },
  {
    date: '4 June 2026',
    title: 'Implement PWA with offline support',
    status: 'moderate',
    type: 'update',
    version: '1.2.0',
    description: 'Added manifest.json, service worker with network-first caching, offline.html fallback. App now installable on mobile and desktop.',
  },
  {
    date: '4 June 2026',
    title: 'Revamp Update Log system & add LogCard component',
    status: 'moderate',
    type: 'revamp',
    version: '1.1.0',
    description: 'Restructured log data with status/type/version fields. Created LogCard with accordion, color-coded badges, and hover tooltips.',
  },
  {
    date: '2 June 2026',
    title: 'Complete rebuild with TanStack Start + TypeScript + cinematic design system',
    status: 'major',
    type: 'refactor',
    version: '1.0.0',
    description: 'Full migration to TanStack Start + SSR + Nitro. Cinematic dark design system inspired by Riot Games. TypeScript strict mode.',
  },
  {
    date: '18 September 2025',
    title: 'Installing new fonts + change update log data to constant',
    status: 'minor',
    type: 'update',
    version: '0.4.3',
    description: 'Added custom fonts (Inter, JetBrains Mono) and migrated update log data to a dedicated constants file.',
  },
  {
    date: '9 Februari 2025',
    title: 'Update post-body-content',
    status: 'minor',
    type: 'update',
    version: '0.4.2',
    description: 'Updated post page formatting.',
  },
  {
    date: '9 Februari 2025',
    title: 'Fixing Loading and Vercel go-to-specific-routes bug',
    status: 'minor',
    type: 'fixing',
    version: '0.4.1',
    description: 'Fixed Vercel configuration for direct route navigation.',
  },
  {
    date: '8 Februari 2025',
    title: 'Fixing post page layout, body-content-HTML, and post card',
    status: 'moderate',
    type: 'fixing',
    version: '0.4.0',
    description: 'Fixed post page format to match rich-text-editor data output.',
  },
  {
    date: '8 Februari 2025',
    title: 'Add Update log & Implement React-helmet',
    status: 'moderate',
    type: 'update',
    version: '0.3.0',
    description: 'Added log page for tracking website updates. Implemented react-helmet for async page titles.',
  },
  {
    date: '8 Februari 2025',
    title: 'Revamp UI, styling, and layout. Add new webLogo & page animation',
    status: 'minor',
    type: 'refactor',
    version: '0.2.1',
    description: 'Revamped UI & layout. Added new Feldora logo and page transition animations.',
  },
  {
    date: '2 Agustus 2024',
    title: 'Implement GetPost and post page using React Query and GraphQL',
    status: 'moderate',
    type: 'update',
    version: '0.2.0',
    description: 'Integrated React Query with Hygraph GraphQL API for post fetching.',
  },
  {
    date: '22 Juli 2024',
    title: 'Initialize React Query',
    status: 'moderate',
    type: 'update',
    version: '0.1.0',
    description: 'Installed and configured React Query. Set development rules & standards.',
  },
  {
    date: '9 Juli 2024',
    title: 'Initialize Project',
    status: 'major',
    type: 'update',
    version: '0.0.0',
    description: 'Initialized Feldora with Vite + React. Planned react-query for data fetching & state management.',
  },
]
