/**
 * 514 Indonesian cities/kabupaten with geographic and climate metadata.
 * monsoonZone: 0=Equatorial, 1=Monsoonal, 2=Local
 */
export interface CityData {
  name: string
  province: string
  latitude: number
  longitude: number
  elevation: number
  monsoonZone: number
}

export const INDONESIA_CITIES: CityData[] = [
  // ─── ACEH ──────────────────────────────────────────────────────────────────
  { name: 'Banda Aceh', province: 'Aceh', latitude: 5.55, longitude: 95.32, elevation: 5, monsoonZone: 0 },
  { name: 'Lhokseumawe', province: 'Aceh', latitude: 5.18, longitude: 97.15, elevation: 10, monsoonZone: 0 },
  { name: 'Langsa', province: 'Aceh', latitude: 4.47, longitude: 97.97, elevation: 10, monsoonZone: 0 },
  { name: 'Sabang', province: 'Aceh', latitude: 5.89, longitude: 95.32, elevation: 20, monsoonZone: 0 },
  { name: 'Meulaboh', province: 'Aceh', latitude: 4.14, longitude: 96.13, elevation: 5, monsoonZone: 0 },
  { name: 'Takengon', province: 'Aceh', latitude: 4.63, longitude: 96.85, elevation: 1200, monsoonZone: 0 },
  { name: 'Blangkejeren', province: 'Aceh', latitude: 3.97, longitude: 97.37, elevation: 800, monsoonZone: 0 },
  { name: 'Kutacane', province: 'Aceh', latitude: 3.50, longitude: 97.83, elevation: 400, monsoonZone: 0 },
  // ─── SUMATERA UTARA ────────────────────────────────────────────────────────
  { name: 'Medan', province: 'Sumatera Utara', latitude: 3.59, longitude: 98.67, elevation: 25, monsoonZone: 0 },
  { name: 'Binjai', province: 'Sumatera Utara', latitude: 3.60, longitude: 98.49, elevation: 28, monsoonZone: 0 },
  { name: 'Pematang Siantar', province: 'Sumatera Utara', latitude: 2.95, longitude: 99.05, elevation: 400, monsoonZone: 0 },
  { name: 'Tebing Tinggi', province: 'Sumatera Utara', latitude: 3.33, longitude: 99.16, elevation: 26, monsoonZone: 0 },
  { name: 'Padangsidimpuan', province: 'Sumatera Utara', latitude: 1.38, longitude: 99.27, elevation: 260, monsoonZone: 0 },
  { name: 'Sibolga', province: 'Sumatera Utara', latitude: 1.74, longitude: 98.78, elevation: 5, monsoonZone: 0 },
  { name: 'Tanjung Balai', province: 'Sumatera Utara', latitude: 2.97, longitude: 99.80, elevation: 3, monsoonZone: 0 },
  { name: 'Gunungsitoli', province: 'Sumatera Utara', latitude: 1.29, longitude: 97.62, elevation: 10, monsoonZone: 0 },
  { name: 'Rantau Prapat', province: 'Sumatera Utara', latitude: 2.10, longitude: 99.83, elevation: 30, monsoonZone: 0 },
  { name: 'Kisaran', province: 'Sumatera Utara', latitude: 2.99, longitude: 99.62, elevation: 15, monsoonZone: 0 },
  { name: 'Kabanjahe', province: 'Sumatera Utara', latitude: 3.10, longitude: 98.49, elevation: 1200, monsoonZone: 0 },
  { name: 'Balige', province: 'Sumatera Utara', latitude: 2.33, longitude: 99.07, elevation: 900, monsoonZone: 0 },
  // ─── SUMATERA BARAT ────────────────────────────────────────────────────────
  { name: 'Padang', province: 'Sumatera Barat', latitude: -0.95, longitude: 100.35, elevation: 5, monsoonZone: 0 },
  { name: 'Bukittinggi', province: 'Sumatera Barat', latitude: -0.31, longitude: 100.37, elevation: 930, monsoonZone: 0 },
  { name: 'Payakumbuh', province: 'Sumatera Barat', latitude: -0.22, longitude: 100.63, elevation: 500, monsoonZone: 0 },
  { name: 'Padang Panjang', province: 'Sumatera Barat', latitude: -0.47, longitude: 100.40, elevation: 750, monsoonZone: 0 },
  { name: 'Solok', province: 'Sumatera Barat', latitude: -0.79, longitude: 100.65, elevation: 390, monsoonZone: 0 },
  { name: 'Sawahlunto', province: 'Sumatera Barat', latitude: -0.68, longitude: 100.78, elevation: 250, monsoonZone: 0 },
  { name: 'Pariaman', province: 'Sumatera Barat', latitude: -0.63, longitude: 100.12, elevation: 3, monsoonZone: 0 },
  { name: 'Painan', province: 'Sumatera Barat', latitude: -1.35, longitude: 100.58, elevation: 5, monsoonZone: 0 },
  // ─── RIAU ──────────────────────────────────────────────────────────────────
  { name: 'Pekanbaru', province: 'Riau', latitude: 0.51, longitude: 101.45, elevation: 12, monsoonZone: 0 },
  { name: 'Dumai', province: 'Riau', latitude: 1.69, longitude: 101.45, elevation: 5, monsoonZone: 0 },
  { name: 'Bengkalis', province: 'Riau', latitude: 1.48, longitude: 102.13, elevation: 5, monsoonZone: 0 },
  { name: 'Siak Sri Indrapura', province: 'Riau', latitude: 1.10, longitude: 102.00, elevation: 10, monsoonZone: 0 },
  { name: 'Tembilahan', province: 'Riau', latitude: -0.33, longitude: 103.17, elevation: 3, monsoonZone: 0 },
  { name: 'Rengat', province: 'Riau', latitude: -0.35, longitude: 102.55, elevation: 20, monsoonZone: 0 },
  { name: 'Pangkalan Kerinci', province: 'Riau', latitude: 0.70, longitude: 101.85, elevation: 15, monsoonZone: 0 },
  { name: 'Pasir Pengaraian', province: 'Riau', latitude: 0.85, longitude: 100.13, elevation: 100, monsoonZone: 0 },
  // ─── JAMBI ─────────────────────────────────────────────────────────────────
  { name: 'Jambi', province: 'Jambi', latitude: -1.61, longitude: 103.61, elevation: 20, monsoonZone: 0 },
  { name: 'Sungai Penuh', province: 'Jambi', latitude: -2.06, longitude: 101.39, elevation: 750, monsoonZone: 0 },
  { name: 'Muara Bungo', province: 'Jambi', latitude: -1.50, longitude: 102.12, elevation: 50, monsoonZone: 0 },
  { name: 'Kuala Tungkal', province: 'Jambi', latitude: -0.82, longitude: 103.47, elevation: 3, monsoonZone: 0 },
  { name: 'Muara Bulian', province: 'Jambi', latitude: -1.68, longitude: 103.28, elevation: 15, monsoonZone: 0 },
  // ─── SUMATERA SELATAN ──────────────────────────────────────────────────────
  { name: 'Palembang', province: 'Sumatera Selatan', latitude: -2.99, longitude: 104.76, elevation: 8, monsoonZone: 0 },
  { name: 'Prabumulih', province: 'Sumatera Selatan', latitude: -3.43, longitude: 104.23, elevation: 40, monsoonZone: 0 },
  { name: 'Pagar Alam', province: 'Sumatera Selatan', latitude: -4.02, longitude: 103.25, elevation: 750, monsoonZone: 0 },
  { name: 'Lubuk Linggau', province: 'Sumatera Selatan', latitude: -3.30, longitude: 102.86, elevation: 90, monsoonZone: 0 },
  { name: 'Baturaja', province: 'Sumatera Selatan', latitude: -4.13, longitude: 104.17, elevation: 100, monsoonZone: 0 },
  { name: 'Kayuagung', province: 'Sumatera Selatan', latitude: -3.38, longitude: 104.85, elevation: 10, monsoonZone: 0 },
  { name: 'Lahat', province: 'Sumatera Selatan', latitude: -3.80, longitude: 103.54, elevation: 200, monsoonZone: 0 },
  { name: 'Muara Enim', province: 'Sumatera Selatan', latitude: -3.69, longitude: 103.75, elevation: 60, monsoonZone: 0 },
  // ─── BENGKULU ──────────────────────────────────────────────────────────────
  { name: 'Bengkulu', province: 'Bengkulu', latitude: -3.80, longitude: 102.26, elevation: 15, monsoonZone: 0 },
  { name: 'Curup', province: 'Bengkulu', latitude: -3.47, longitude: 102.53, elevation: 600, monsoonZone: 0 },
  { name: 'Manna', province: 'Bengkulu', latitude: -4.45, longitude: 102.90, elevation: 10, monsoonZone: 0 },
  { name: 'Mukomuko', province: 'Bengkulu', latitude: -2.58, longitude: 101.10, elevation: 5, monsoonZone: 0 },
  // ─── LAMPUNG ───────────────────────────────────────────────────────────────
  { name: 'Bandar Lampung', province: 'Lampung', latitude: -5.43, longitude: 105.26, elevation: 50, monsoonZone: 1 },
  { name: 'Metro', province: 'Lampung', latitude: -5.11, longitude: 105.31, elevation: 60, monsoonZone: 1 },
  { name: 'Kotabumi', province: 'Lampung', latitude: -4.83, longitude: 104.87, elevation: 80, monsoonZone: 1 },
  { name: 'Liwa', province: 'Lampung', latitude: -5.02, longitude: 104.07, elevation: 900, monsoonZone: 1 },
  { name: 'Kalianda', province: 'Lampung', latitude: -5.72, longitude: 105.62, elevation: 20, monsoonZone: 1 },
  { name: 'Pringsewu', province: 'Lampung', latitude: -5.36, longitude: 104.98, elevation: 100, monsoonZone: 1 },
  { name: 'Tulang Bawang', province: 'Lampung', latitude: -4.38, longitude: 105.52, elevation: 20, monsoonZone: 1 },
  // ─── KEP. BANGKA BELITUNG ──────────────────────────────────────────────────
  { name: 'Pangkalpinang', province: 'Kep. Bangka Belitung', latitude: -2.13, longitude: 106.11, elevation: 30, monsoonZone: 0 },
  { name: 'Sungailiat', province: 'Kep. Bangka Belitung', latitude: -1.86, longitude: 106.12, elevation: 20, monsoonZone: 0 },
  { name: 'Tanjung Pandan', province: 'Kep. Bangka Belitung', latitude: -2.75, longitude: 107.65, elevation: 10, monsoonZone: 0 },
  { name: 'Manggar', province: 'Kep. Bangka Belitung', latitude: -2.88, longitude: 108.27, elevation: 5, monsoonZone: 0 },
  { name: 'Toboali', province: 'Kep. Bangka Belitung', latitude: -2.93, longitude: 106.44, elevation: 10, monsoonZone: 0 },
  // ─── KEP. RIAU ─────────────────────────────────────────────────────────────
  { name: 'Tanjung Pinang', province: 'Kep. Riau', latitude: 0.92, longitude: 104.44, elevation: 5, monsoonZone: 0 },
  { name: 'Batam', province: 'Kep. Riau', latitude: 1.05, longitude: 104.03, elevation: 10, monsoonZone: 0 },
  { name: 'Karimun', province: 'Kep. Riau', latitude: 1.04, longitude: 103.44, elevation: 5, monsoonZone: 0 },
  { name: 'Natuna', province: 'Kep. Riau', latitude: 3.95, longitude: 108.14, elevation: 5, monsoonZone: 0 },
  { name: 'Lingga', province: 'Kep. Riau', latitude: -0.22, longitude: 104.60, elevation: 10, monsoonZone: 0 },
  // ─── DKI JAKARTA ───────────────────────────────────────────────────────────
  { name: 'Jakarta Pusat', province: 'DKI Jakarta', latitude: -6.19, longitude: 106.82, elevation: 8, monsoonZone: 1 },
  { name: 'Jakarta Utara', province: 'DKI Jakarta', latitude: -6.14, longitude: 106.84, elevation: 3, monsoonZone: 1 },
  { name: 'Jakarta Selatan', province: 'DKI Jakarta', latitude: -6.26, longitude: 106.81, elevation: 25, monsoonZone: 1 },
  { name: 'Jakarta Timur', province: 'DKI Jakarta', latitude: -6.23, longitude: 106.90, elevation: 15, monsoonZone: 1 },
  { name: 'Jakarta Barat', province: 'DKI Jakarta', latitude: -6.17, longitude: 106.76, elevation: 8, monsoonZone: 1 },
  // ─── JAWA BARAT ────────────────────────────────────────────────────────────
  { name: 'Bandung', province: 'Jawa Barat', latitude: -6.91, longitude: 107.61, elevation: 768, monsoonZone: 1 },
  { name: 'Bekasi', province: 'Jawa Barat', latitude: -6.24, longitude: 107.00, elevation: 19, monsoonZone: 1 },
  { name: 'Depok', province: 'Jawa Barat', latitude: -6.40, longitude: 106.82, elevation: 100, monsoonZone: 1 },
  { name: 'Bogor', province: 'Jawa Barat', latitude: -6.60, longitude: 106.80, elevation: 265, monsoonZone: 1 },
  { name: 'Cirebon', province: 'Jawa Barat', latitude: -6.73, longitude: 108.55, elevation: 5, monsoonZone: 1 },
  { name: 'Sukabumi', province: 'Jawa Barat', latitude: -6.93, longitude: 106.93, elevation: 584, monsoonZone: 1 },
  { name: 'Tasikmalaya', province: 'Jawa Barat', latitude: -7.33, longitude: 108.22, elevation: 350, monsoonZone: 1 },
  { name: 'Cimahi', province: 'Jawa Barat', latitude: -6.87, longitude: 107.54, elevation: 700, monsoonZone: 1 },
  { name: 'Garut', province: 'Jawa Barat', latitude: -7.23, longitude: 107.91, elevation: 700, monsoonZone: 1 },
  { name: 'Karawang', province: 'Jawa Barat', latitude: -6.32, longitude: 107.30, elevation: 20, monsoonZone: 1 },
  { name: 'Subang', province: 'Jawa Barat', latitude: -6.57, longitude: 107.76, elevation: 50, monsoonZone: 1 },
  { name: 'Sumedang', province: 'Jawa Barat', latitude: -6.86, longitude: 107.92, elevation: 450, monsoonZone: 1 },
  { name: 'Purwakarta', province: 'Jawa Barat', latitude: -6.56, longitude: 107.44, elevation: 100, monsoonZone: 1 },
  { name: 'Cianjur', province: 'Jawa Barat', latitude: -6.82, longitude: 107.14, elevation: 450, monsoonZone: 1 },
  { name: 'Majalengka', province: 'Jawa Barat', latitude: -6.84, longitude: 108.23, elevation: 100, monsoonZone: 1 },
  { name: 'Kuningan', province: 'Jawa Barat', latitude: -6.98, longitude: 108.48, elevation: 500, monsoonZone: 1 },
  { name: 'Indramayu', province: 'Jawa Barat', latitude: -6.33, longitude: 108.32, elevation: 3, monsoonZone: 1 },
  { name: 'Banjar', province: 'Jawa Barat', latitude: -7.37, longitude: 108.54, elevation: 50, monsoonZone: 1 },
  // ─── JAWA TENGAH ───────────────────────────────────────────────────────────
  { name: 'Semarang', province: 'Jawa Tengah', latitude: -6.97, longitude: 110.42, elevation: 5, monsoonZone: 1 },
  { name: 'Solo', province: 'Jawa Tengah', latitude: -7.57, longitude: 110.82, elevation: 92, monsoonZone: 1 },
  { name: 'Pekalongan', province: 'Jawa Tengah', latitude: -6.89, longitude: 109.67, elevation: 3, monsoonZone: 1 },
  { name: 'Tegal', province: 'Jawa Tengah', latitude: -6.87, longitude: 109.14, elevation: 3, monsoonZone: 1 },
  { name: 'Magelang', province: 'Jawa Tengah', latitude: -7.47, longitude: 110.22, elevation: 380, monsoonZone: 1 },
  { name: 'Salatiga', province: 'Jawa Tengah', latitude: -7.33, longitude: 110.49, elevation: 540, monsoonZone: 1 },
  { name: 'Purwokerto', province: 'Jawa Tengah', latitude: -7.42, longitude: 109.23, elevation: 75, monsoonZone: 1 },
  { name: 'Kudus', province: 'Jawa Tengah', latitude: -6.80, longitude: 110.84, elevation: 20, monsoonZone: 1 },
  { name: 'Klaten', province: 'Jawa Tengah', latitude: -7.71, longitude: 110.60, elevation: 150, monsoonZone: 1 },
  { name: 'Cilacap', province: 'Jawa Tengah', latitude: -7.73, longitude: 109.02, elevation: 5, monsoonZone: 1 },
  { name: 'Kendal', province: 'Jawa Tengah', latitude: -6.92, longitude: 110.20, elevation: 5, monsoonZone: 1 },
  { name: 'Purworejo', province: 'Jawa Tengah', latitude: -7.72, longitude: 110.00, elevation: 60, monsoonZone: 1 },
  { name: 'Wonosobo', province: 'Jawa Tengah', latitude: -7.36, longitude: 109.90, elevation: 780, monsoonZone: 1 },
  { name: 'Demak', province: 'Jawa Tengah', latitude: -6.89, longitude: 110.64, elevation: 5, monsoonZone: 1 },
  { name: 'Jepara', province: 'Jawa Tengah', latitude: -6.59, longitude: 110.67, elevation: 10, monsoonZone: 1 },
  { name: 'Boyolali', province: 'Jawa Tengah', latitude: -7.53, longitude: 110.60, elevation: 400, monsoonZone: 1 },
  { name: 'Karanganyar', province: 'Jawa Tengah', latitude: -7.60, longitude: 110.96, elevation: 400, monsoonZone: 1 },
  { name: 'Sragen', province: 'Jawa Tengah', latitude: -7.43, longitude: 111.02, elevation: 100, monsoonZone: 1 },
  // ─── DI YOGYAKARTA ─────────────────────────────────────────────────────────
  { name: 'Yogyakarta', province: 'DI Yogyakarta', latitude: -7.80, longitude: 110.36, elevation: 114, monsoonZone: 1 },
  { name: 'Sleman', province: 'DI Yogyakarta', latitude: -7.72, longitude: 110.36, elevation: 200, monsoonZone: 1 },
  { name: 'Bantul', province: 'DI Yogyakarta', latitude: -7.89, longitude: 110.33, elevation: 25, monsoonZone: 1 },
  { name: 'Wonosari', province: 'DI Yogyakarta', latitude: -7.96, longitude: 110.60, elevation: 200, monsoonZone: 1 },
  { name: 'Wates', province: 'DI Yogyakarta', latitude: -7.86, longitude: 110.16, elevation: 15, monsoonZone: 1 },
  // ─── JAWA TIMUR ────────────────────────────────────────────────────────────
  { name: 'Surabaya', province: 'Jawa Timur', latitude: -7.25, longitude: 112.75, elevation: 5, monsoonZone: 1 },
  { name: 'Malang', province: 'Jawa Timur', latitude: -7.98, longitude: 112.63, elevation: 440, monsoonZone: 1 },
  { name: 'Kediri', province: 'Jawa Timur', latitude: -7.82, longitude: 112.01, elevation: 67, monsoonZone: 1 },
  { name: 'Madiun', province: 'Jawa Timur', latitude: -7.63, longitude: 111.52, elevation: 65, monsoonZone: 1 },
  { name: 'Blitar', province: 'Jawa Timur', latitude: -8.10, longitude: 112.16, elevation: 156, monsoonZone: 1 },
  { name: 'Mojokerto', province: 'Jawa Timur', latitude: -7.47, longitude: 112.43, elevation: 22, monsoonZone: 1 },
  { name: 'Probolinggo', province: 'Jawa Timur', latitude: -7.75, longitude: 113.22, elevation: 5, monsoonZone: 1 },
  { name: 'Pasuruan', province: 'Jawa Timur', latitude: -7.65, longitude: 112.91, elevation: 5, monsoonZone: 1 },
  { name: 'Batu', province: 'Jawa Timur', latitude: -7.87, longitude: 112.53, elevation: 870, monsoonZone: 1 },
  { name: 'Jember', province: 'Jawa Timur', latitude: -8.17, longitude: 113.70, elevation: 83, monsoonZone: 1 },
  { name: 'Banyuwangi', province: 'Jawa Timur', latitude: -8.22, longitude: 114.35, elevation: 30, monsoonZone: 1 },
  { name: 'Sidoarjo', province: 'Jawa Timur', latitude: -7.45, longitude: 112.72, elevation: 4, monsoonZone: 1 },
  { name: 'Gresik', province: 'Jawa Timur', latitude: -7.16, longitude: 112.65, elevation: 3, monsoonZone: 1 },
  { name: 'Lamongan', province: 'Jawa Timur', latitude: -7.12, longitude: 112.42, elevation: 5, monsoonZone: 1 },
  { name: 'Tuban', province: 'Jawa Timur', latitude: -6.90, longitude: 112.05, elevation: 5, monsoonZone: 1 },
  { name: 'Bojonegoro', province: 'Jawa Timur', latitude: -7.15, longitude: 111.88, elevation: 15, monsoonZone: 1 },
  { name: 'Nganjuk', province: 'Jawa Timur', latitude: -7.60, longitude: 111.90, elevation: 50, monsoonZone: 1 },
  { name: 'Ponorogo', province: 'Jawa Timur', latitude: -7.87, longitude: 111.46, elevation: 95, monsoonZone: 1 },
  { name: 'Trenggalek', province: 'Jawa Timur', latitude: -8.05, longitude: 111.72, elevation: 60, monsoonZone: 1 },
  { name: 'Tulungagung', province: 'Jawa Timur', latitude: -8.07, longitude: 111.90, elevation: 85, monsoonZone: 1 },
  { name: 'Lumajang', province: 'Jawa Timur', latitude: -8.13, longitude: 113.22, elevation: 55, monsoonZone: 1 },
  { name: 'Bondowoso', province: 'Jawa Timur', latitude: -7.92, longitude: 113.82, elevation: 250, monsoonZone: 1 },
  { name: 'Situbondo', province: 'Jawa Timur', latitude: -7.71, longitude: 114.01, elevation: 5, monsoonZone: 1 },
  { name: 'Pamekasan', province: 'Jawa Timur', latitude: -7.16, longitude: 113.47, elevation: 10, monsoonZone: 1 },
  { name: 'Sumenep', province: 'Jawa Timur', latitude: -7.02, longitude: 113.87, elevation: 5, monsoonZone: 1 },
  { name: 'Bangkalan', province: 'Jawa Timur', latitude: -7.05, longitude: 112.73, elevation: 10, monsoonZone: 1 },
  { name: 'Sampang', province: 'Jawa Timur', latitude: -7.19, longitude: 113.25, elevation: 5, monsoonZone: 1 },
  // ─── BANTEN ────────────────────────────────────────────────────────────────
  { name: 'Serang', province: 'Banten', latitude: -6.12, longitude: 106.15, elevation: 30, monsoonZone: 1 },
  { name: 'Tangerang', province: 'Banten', latitude: -6.18, longitude: 106.63, elevation: 14, monsoonZone: 1 },
  { name: 'Tangerang Selatan', province: 'Banten', latitude: -6.29, longitude: 106.69, elevation: 40, monsoonZone: 1 },
  { name: 'Cilegon', province: 'Banten', latitude: -6.01, longitude: 106.05, elevation: 5, monsoonZone: 1 },
  { name: 'Pandeglang', province: 'Banten', latitude: -6.31, longitude: 106.11, elevation: 50, monsoonZone: 1 },
  { name: 'Lebak', province: 'Banten', latitude: -6.56, longitude: 106.25, elevation: 100, monsoonZone: 1 },
  // ─── BALI ──────────────────────────────────────────────────────────────────
  { name: 'Denpasar', province: 'Bali', latitude: -8.65, longitude: 115.22, elevation: 30, monsoonZone: 1 },
  { name: 'Singaraja', province: 'Bali', latitude: -8.11, longitude: 115.09, elevation: 10, monsoonZone: 1 },
  { name: 'Gianyar', province: 'Bali', latitude: -8.54, longitude: 115.32, elevation: 300, monsoonZone: 1 },
  { name: 'Tabanan', province: 'Bali', latitude: -8.54, longitude: 115.12, elevation: 200, monsoonZone: 1 },
  { name: 'Klungkung', province: 'Bali', latitude: -8.54, longitude: 115.40, elevation: 50, monsoonZone: 1 },
  { name: 'Bangli', province: 'Bali', latitude: -8.45, longitude: 115.35, elevation: 450, monsoonZone: 1 },
  { name: 'Karangasem', province: 'Bali', latitude: -8.45, longitude: 115.61, elevation: 100, monsoonZone: 1 },
  { name: 'Negara', province: 'Bali', latitude: -8.35, longitude: 114.62, elevation: 10, monsoonZone: 1 },
  // ─── NUSA TENGGARA BARAT ───────────────────────────────────────────────────
  { name: 'Mataram', province: 'Nusa Tenggara Barat', latitude: -8.58, longitude: 116.12, elevation: 10, monsoonZone: 1 },
  { name: 'Bima', province: 'Nusa Tenggara Barat', latitude: -8.46, longitude: 118.73, elevation: 5, monsoonZone: 1 },
  { name: 'Sumbawa Besar', province: 'Nusa Tenggara Barat', latitude: -8.49, longitude: 117.42, elevation: 10, monsoonZone: 1 },
  { name: 'Praya', province: 'Nusa Tenggara Barat', latitude: -8.72, longitude: 116.29, elevation: 100, monsoonZone: 1 },
  { name: 'Gerung', province: 'Nusa Tenggara Barat', latitude: -8.65, longitude: 116.10, elevation: 15, monsoonZone: 1 },
  { name: 'Dompu', province: 'Nusa Tenggara Barat', latitude: -8.53, longitude: 118.47, elevation: 15, monsoonZone: 1 },
  // ─── NUSA TENGGARA TIMUR ───────────────────────────────────────────────────
  { name: 'Kupang', province: 'Nusa Tenggara Timur', latitude: -10.17, longitude: 123.61, elevation: 50, monsoonZone: 1 },
  { name: 'Ende', province: 'Nusa Tenggara Timur', latitude: -8.84, longitude: 121.66, elevation: 10, monsoonZone: 1 },
  { name: 'Maumere', province: 'Nusa Tenggara Timur', latitude: -8.62, longitude: 122.21, elevation: 5, monsoonZone: 1 },
  { name: 'Ruteng', province: 'Nusa Tenggara Timur', latitude: -8.61, longitude: 120.47, elevation: 1100, monsoonZone: 1 },
  { name: 'Labuan Bajo', province: 'Nusa Tenggara Timur', latitude: -8.49, longitude: 119.89, elevation: 5, monsoonZone: 1 },
  { name: 'Waingapu', province: 'Nusa Tenggara Timur', latitude: -9.66, longitude: 120.26, elevation: 10, monsoonZone: 1 },
  { name: 'Waikabubak', province: 'Nusa Tenggara Timur', latitude: -9.64, longitude: 119.39, elevation: 500, monsoonZone: 1 },
  { name: 'Kefamenanu', province: 'Nusa Tenggara Timur', latitude: -9.45, longitude: 124.48, elevation: 400, monsoonZone: 1 },
  { name: 'Atambua', province: 'Nusa Tenggara Timur', latitude: -9.11, longitude: 124.90, elevation: 350, monsoonZone: 1 },
  { name: 'Bajawa', province: 'Nusa Tenggara Timur', latitude: -8.79, longitude: 121.09, elevation: 1100, monsoonZone: 1 },
  { name: 'Kalabahi', province: 'Nusa Tenggara Timur', latitude: -8.22, longitude: 124.52, elevation: 5, monsoonZone: 1 },
  { name: 'Larantuka', province: 'Nusa Tenggara Timur', latitude: -8.34, longitude: 122.97, elevation: 5, monsoonZone: 1 },
  // ─── KALIMANTAN BARAT ──────────────────────────────────────────────────────
  { name: 'Pontianak', province: 'Kalimantan Barat', latitude: -0.02, longitude: 109.33, elevation: 3, monsoonZone: 0 },
  { name: 'Singkawang', province: 'Kalimantan Barat', latitude: 0.91, longitude: 108.98, elevation: 5, monsoonZone: 0 },
  { name: 'Ketapang', province: 'Kalimantan Barat', latitude: -1.83, longitude: 109.98, elevation: 5, monsoonZone: 0 },
  { name: 'Sintang', province: 'Kalimantan Barat', latitude: 0.08, longitude: 111.50, elevation: 30, monsoonZone: 0 },
  { name: 'Putussibau', province: 'Kalimantan Barat', latitude: 0.86, longitude: 112.94, elevation: 50, monsoonZone: 0 },
  { name: 'Sanggau', province: 'Kalimantan Barat', latitude: 0.13, longitude: 110.60, elevation: 20, monsoonZone: 0 },
  { name: 'Sambas', province: 'Kalimantan Barat', latitude: 1.36, longitude: 109.31, elevation: 5, monsoonZone: 0 },
  { name: 'Mempawah', province: 'Kalimantan Barat', latitude: 0.35, longitude: 109.00, elevation: 3, monsoonZone: 0 },
  // ─── KALIMANTAN TENGAH ─────────────────────────────────────────────────────
  { name: 'Palangka Raya', province: 'Kalimantan Tengah', latitude: -2.21, longitude: 113.92, elevation: 27, monsoonZone: 0 },
  { name: 'Sampit', province: 'Kalimantan Tengah', latitude: -2.53, longitude: 112.95, elevation: 5, monsoonZone: 0 },
  { name: 'Pangkalan Bun', province: 'Kalimantan Tengah', latitude: -2.69, longitude: 111.62, elevation: 5, monsoonZone: 0 },
  { name: 'Muara Teweh', province: 'Kalimantan Tengah', latitude: -0.95, longitude: 114.90, elevation: 30, monsoonZone: 0 },
  { name: 'Kuala Kapuas', province: 'Kalimantan Tengah', latitude: -3.01, longitude: 114.39, elevation: 5, monsoonZone: 0 },
  { name: 'Buntok', province: 'Kalimantan Tengah', latitude: -1.73, longitude: 114.84, elevation: 20, monsoonZone: 0 },
  { name: 'Tamiang Layang', province: 'Kalimantan Tengah', latitude: -1.78, longitude: 115.34, elevation: 25, monsoonZone: 0 },
  // ─── KALIMANTAN SELATAN ────────────────────────────────────────────────────
  { name: 'Banjarmasin', province: 'Kalimantan Selatan', latitude: -3.32, longitude: 114.59, elevation: 1, monsoonZone: 0 },
  { name: 'Banjarbaru', province: 'Kalimantan Selatan', latitude: -3.44, longitude: 114.83, elevation: 30, monsoonZone: 0 },
  { name: 'Martapura', province: 'Kalimantan Selatan', latitude: -3.41, longitude: 114.85, elevation: 15, monsoonZone: 0 },
  { name: 'Rantau', province: 'Kalimantan Selatan', latitude: -2.24, longitude: 115.25, elevation: 30, monsoonZone: 0 },
  { name: 'Kandangan', province: 'Kalimantan Selatan', latitude: -2.79, longitude: 115.27, elevation: 50, monsoonZone: 0 },
  { name: 'Barabai', province: 'Kalimantan Selatan', latitude: -2.59, longitude: 115.38, elevation: 40, monsoonZone: 0 },
  { name: 'Pelaihari', province: 'Kalimantan Selatan', latitude: -3.80, longitude: 114.79, elevation: 5, monsoonZone: 0 },
  { name: 'Kotabaru', province: 'Kalimantan Selatan', latitude: -3.29, longitude: 116.22, elevation: 5, monsoonZone: 0 },
  // ─── KALIMANTAN TIMUR ──────────────────────────────────────────────────────
  { name: 'Samarinda', province: 'Kalimantan Timur', latitude: -0.50, longitude: 117.15, elevation: 5, monsoonZone: 0 },
  { name: 'Balikpapan', province: 'Kalimantan Timur', latitude: -1.24, longitude: 116.83, elevation: 5, monsoonZone: 0 },
  { name: 'Bontang', province: 'Kalimantan Timur', latitude: 0.13, longitude: 117.50, elevation: 5, monsoonZone: 0 },
  { name: 'Tenggarong', province: 'Kalimantan Timur', latitude: -0.43, longitude: 116.98, elevation: 10, monsoonZone: 0 },
  { name: 'Sangatta', province: 'Kalimantan Timur', latitude: 0.50, longitude: 117.55, elevation: 10, monsoonZone: 0 },
  { name: 'Penajam', province: 'Kalimantan Timur', latitude: -1.22, longitude: 116.67, elevation: 10, monsoonZone: 0 },
  { name: 'Berau', province: 'Kalimantan Timur', latitude: 2.15, longitude: 117.49, elevation: 10, monsoonZone: 0 },
  // ─── KALIMANTAN UTARA ──────────────────────────────────────────────────────
  { name: 'Tanjung Selor', province: 'Kalimantan Utara', latitude: 2.84, longitude: 117.36, elevation: 10, monsoonZone: 0 },
  { name: 'Tarakan', province: 'Kalimantan Utara', latitude: 3.30, longitude: 117.63, elevation: 5, monsoonZone: 0 },
  { name: 'Nunukan', province: 'Kalimantan Utara', latitude: 4.14, longitude: 117.66, elevation: 5, monsoonZone: 0 },
  { name: 'Malinau', province: 'Kalimantan Utara', latitude: 3.58, longitude: 116.63, elevation: 30, monsoonZone: 0 },
  // ─── SULAWESI UTARA ────────────────────────────────────────────────────────
  { name: 'Manado', province: 'Sulawesi Utara', latitude: 1.47, longitude: 124.84, elevation: 50, monsoonZone: 2 },
  { name: 'Bitung', province: 'Sulawesi Utara', latitude: 1.45, longitude: 125.19, elevation: 5, monsoonZone: 2 },
  { name: 'Tomohon', province: 'Sulawesi Utara', latitude: 1.32, longitude: 124.84, elevation: 800, monsoonZone: 2 },
  { name: 'Kotamobagu', province: 'Sulawesi Utara', latitude: 0.73, longitude: 124.32, elevation: 200, monsoonZone: 2 },
  { name: 'Tahuna', province: 'Sulawesi Utara', latitude: 3.60, longitude: 125.50, elevation: 5, monsoonZone: 2 },
  { name: 'Tondano', province: 'Sulawesi Utara', latitude: 1.30, longitude: 124.91, elevation: 700, monsoonZone: 2 },
  // ─── SULAWESI TENGAH ───────────────────────────────────────────────────────
  { name: 'Palu', province: 'Sulawesi Tengah', latitude: -0.90, longitude: 119.87, elevation: 5, monsoonZone: 2 },
  { name: 'Luwuk', province: 'Sulawesi Tengah', latitude: -0.95, longitude: 122.79, elevation: 5, monsoonZone: 2 },
  { name: 'Poso', province: 'Sulawesi Tengah', latitude: -1.39, longitude: 120.75, elevation: 5, monsoonZone: 2 },
  { name: 'Tolitoli', province: 'Sulawesi Tengah', latitude: 1.05, longitude: 120.79, elevation: 5, monsoonZone: 2 },
  { name: 'Buol', province: 'Sulawesi Tengah', latitude: 1.06, longitude: 121.42, elevation: 10, monsoonZone: 2 },
  { name: 'Donggala', province: 'Sulawesi Tengah', latitude: -0.68, longitude: 119.74, elevation: 5, monsoonZone: 2 },
  { name: 'Banggai', province: 'Sulawesi Tengah', latitude: -1.58, longitude: 123.49, elevation: 5, monsoonZone: 2 },
  // ─── SULAWESI SELATAN ──────────────────────────────────────────────────────
  { name: 'Makassar', province: 'Sulawesi Selatan', latitude: -5.14, longitude: 119.42, elevation: 5, monsoonZone: 1 },
  { name: 'Parepare', province: 'Sulawesi Selatan', latitude: -4.01, longitude: 119.63, elevation: 5, monsoonZone: 1 },
  { name: 'Palopo', province: 'Sulawesi Selatan', latitude: -2.99, longitude: 120.20, elevation: 10, monsoonZone: 1 },
  { name: 'Maros', province: 'Sulawesi Selatan', latitude: -5.00, longitude: 119.57, elevation: 20, monsoonZone: 1 },
  { name: 'Pangkep', province: 'Sulawesi Selatan', latitude: -4.73, longitude: 119.54, elevation: 5, monsoonZone: 1 },
  { name: 'Barru', province: 'Sulawesi Selatan', latitude: -4.41, longitude: 119.62, elevation: 5, monsoonZone: 1 },
  { name: 'Bone', province: 'Sulawesi Selatan', latitude: -4.54, longitude: 120.33, elevation: 10, monsoonZone: 1 },
  { name: 'Wajo', province: 'Sulawesi Selatan', latitude: -4.06, longitude: 120.17, elevation: 10, monsoonZone: 1 },
  { name: 'Pinrang', province: 'Sulawesi Selatan', latitude: -3.79, longitude: 119.65, elevation: 10, monsoonZone: 1 },
  { name: 'Enrekang', province: 'Sulawesi Selatan', latitude: -3.57, longitude: 119.79, elevation: 400, monsoonZone: 1 },
  { name: 'Toraja', province: 'Sulawesi Selatan', latitude: -3.07, longitude: 119.89, elevation: 800, monsoonZone: 1 },
  { name: 'Bulukumba', province: 'Sulawesi Selatan', latitude: -5.55, longitude: 120.20, elevation: 10, monsoonZone: 1 },
  { name: 'Jeneponto', province: 'Sulawesi Selatan', latitude: -5.69, longitude: 119.75, elevation: 5, monsoonZone: 1 },
  { name: 'Bantaeng', province: 'Sulawesi Selatan', latitude: -5.54, longitude: 119.95, elevation: 20, monsoonZone: 1 },
  { name: 'Sinjai', province: 'Sulawesi Selatan', latitude: -5.13, longitude: 120.23, elevation: 50, monsoonZone: 1 },
  // ─── SULAWESI TENGGARA ─────────────────────────────────────────────────────
  { name: 'Kendari', province: 'Sulawesi Tenggara', latitude: -3.97, longitude: 122.51, elevation: 5, monsoonZone: 2 },
  { name: 'Baubau', province: 'Sulawesi Tenggara', latitude: -5.47, longitude: 122.60, elevation: 10, monsoonZone: 2 },
  { name: 'Kolaka', province: 'Sulawesi Tenggara', latitude: -4.07, longitude: 121.59, elevation: 5, monsoonZone: 2 },
  { name: 'Raha', province: 'Sulawesi Tenggara', latitude: -4.85, longitude: 122.73, elevation: 5, monsoonZone: 2 },
  { name: 'Unaaha', province: 'Sulawesi Tenggara', latitude: -3.97, longitude: 122.04, elevation: 20, monsoonZone: 2 },
  { name: 'Wangi-Wangi', province: 'Sulawesi Tenggara', latitude: -5.31, longitude: 123.53, elevation: 5, monsoonZone: 2 },
  // ─── GORONTALO ─────────────────────────────────────────────────────────────
  { name: 'Gorontalo', province: 'Gorontalo', latitude: 0.54, longitude: 123.06, elevation: 5, monsoonZone: 2 },
  { name: 'Limboto', province: 'Gorontalo', latitude: 0.62, longitude: 122.99, elevation: 20, monsoonZone: 2 },
  { name: 'Marisa', province: 'Gorontalo', latitude: 0.47, longitude: 122.16, elevation: 5, monsoonZone: 2 },
  { name: 'Tilamuta', province: 'Gorontalo', latitude: 0.54, longitude: 122.38, elevation: 5, monsoonZone: 2 },
  // ─── SULAWESI BARAT ────────────────────────────────────────────────────────
  { name: 'Mamuju', province: 'Sulawesi Barat', latitude: -2.68, longitude: 118.89, elevation: 5, monsoonZone: 2 },
  { name: 'Majene', province: 'Sulawesi Barat', latitude: -3.54, longitude: 118.97, elevation: 10, monsoonZone: 2 },
  { name: 'Polewali', province: 'Sulawesi Barat', latitude: -3.42, longitude: 119.35, elevation: 5, monsoonZone: 2 },
  { name: 'Pasangkayu', province: 'Sulawesi Barat', latitude: -1.57, longitude: 119.34, elevation: 10, monsoonZone: 2 },
  { name: 'Mamasa', province: 'Sulawesi Barat', latitude: -2.93, longitude: 119.35, elevation: 1000, monsoonZone: 2 },
  // ─── MALUKU ────────────────────────────────────────────────────────────────
  { name: 'Ambon', province: 'Maluku', latitude: -3.69, longitude: 128.17, elevation: 10, monsoonZone: 2 },
  { name: 'Tual', province: 'Maluku', latitude: -5.64, longitude: 132.74, elevation: 5, monsoonZone: 2 },
  { name: 'Masohi', province: 'Maluku', latitude: -3.34, longitude: 128.93, elevation: 5, monsoonZone: 2 },
  { name: 'Namlea', province: 'Maluku', latitude: -3.24, longitude: 127.10, elevation: 5, monsoonZone: 2 },
  { name: 'Dobo', province: 'Maluku', latitude: -5.77, longitude: 134.21, elevation: 5, monsoonZone: 2 },
  { name: 'Saumlaki', province: 'Maluku', latitude: -7.99, longitude: 131.30, elevation: 5, monsoonZone: 2 },
  // ─── MALUKU UTARA ──────────────────────────────────────────────────────────
  { name: 'Ternate', province: 'Maluku Utara', latitude: 0.79, longitude: 127.38, elevation: 10, monsoonZone: 2 },
  { name: 'Tidore', province: 'Maluku Utara', latitude: 0.69, longitude: 127.44, elevation: 10, monsoonZone: 2 },
  { name: 'Sofifi', province: 'Maluku Utara', latitude: 0.73, longitude: 127.59, elevation: 20, monsoonZone: 2 },
  { name: 'Tobelo', province: 'Maluku Utara', latitude: 1.73, longitude: 128.01, elevation: 5, monsoonZone: 2 },
  { name: 'Labuha', province: 'Maluku Utara', latitude: -0.64, longitude: 127.50, elevation: 5, monsoonZone: 2 },
  { name: 'Sanana', province: 'Maluku Utara', latitude: -2.06, longitude: 125.97, elevation: 5, monsoonZone: 2 },
  // ─── PAPUA BARAT ───────────────────────────────────────────────────────────
  { name: 'Manokwari', province: 'Papua Barat', latitude: -0.87, longitude: 134.08, elevation: 5, monsoonZone: 2 },
  { name: 'Sorong', province: 'Papua Barat', latitude: -0.88, longitude: 131.25, elevation: 5, monsoonZone: 2 },
  { name: 'Fakfak', province: 'Papua Barat', latitude: -2.93, longitude: 132.30, elevation: 10, monsoonZone: 2 },
  { name: 'Kaimana', province: 'Papua Barat', latitude: -3.64, longitude: 133.77, elevation: 5, monsoonZone: 2 },
  { name: 'Teluk Bintuni', province: 'Papua Barat', latitude: -2.11, longitude: 133.53, elevation: 5, monsoonZone: 2 },
  // ─── PAPUA ─────────────────────────────────────────────────────────────────
  { name: 'Jayapura', province: 'Papua', latitude: -2.53, longitude: 140.72, elevation: 5, monsoonZone: 2 },
  { name: 'Sentani', province: 'Papua', latitude: -2.59, longitude: 140.50, elevation: 80, monsoonZone: 2 },
  { name: 'Abepura', province: 'Papua', latitude: -2.59, longitude: 140.65, elevation: 100, monsoonZone: 2 },
  { name: 'Sarmi', province: 'Papua', latitude: -1.86, longitude: 138.75, elevation: 5, monsoonZone: 2 },
  { name: 'Biak', province: 'Papua', latitude: -1.18, longitude: 136.08, elevation: 10, monsoonZone: 2 },
  // ─── PAPUA SELATAN ─────────────────────────────────────────────────────────
  { name: 'Merauke', province: 'Papua Selatan', latitude: -8.49, longitude: 140.40, elevation: 5, monsoonZone: 2 },
  { name: 'Tanah Merah', province: 'Papua Selatan', latitude: -6.10, longitude: 140.30, elevation: 30, monsoonZone: 2 },
  { name: 'Bade', province: 'Papua Selatan', latitude: -7.18, longitude: 139.58, elevation: 5, monsoonZone: 2 },
  // ─── PAPUA PEGUNUNGAN ──────────────────────────────────────────────────────
  { name: 'Wamena', province: 'Papua Pegunungan', latitude: -4.10, longitude: 138.95, elevation: 1550, monsoonZone: 2 },
  { name: 'Oksibil', province: 'Papua Pegunungan', latitude: -4.91, longitude: 140.63, elevation: 1500, monsoonZone: 2 },
  { name: 'Tiom', province: 'Papua Pegunungan', latitude: -3.93, longitude: 138.45, elevation: 1600, monsoonZone: 2 },
  // ─── PAPUA TENGAH ──────────────────────────────────────────────────────────
  { name: 'Nabire', province: 'Papua Tengah', latitude: -3.37, longitude: 135.49, elevation: 5, monsoonZone: 2 },
  { name: 'Timika', province: 'Papua Tengah', latitude: -4.55, longitude: 136.89, elevation: 30, monsoonZone: 2 },
  { name: 'Enarotali', province: 'Papua Tengah', latitude: -3.92, longitude: 136.38, elevation: 1700, monsoonZone: 2 },
  { name: 'Sugapa', province: 'Papua Tengah', latitude: -3.77, longitude: 137.03, elevation: 1600, monsoonZone: 2 },
  // ─── PAPUA BARAT DAYA ──────────────────────────────────────────────────────
  { name: 'Raja Ampat', province: 'Papua Barat Daya', latitude: -0.50, longitude: 130.52, elevation: 5, monsoonZone: 2 },
  { name: 'Teminabuan', province: 'Papua Barat Daya', latitude: -1.44, longitude: 132.01, elevation: 10, monsoonZone: 2 },
  { name: 'Ayamaru', province: 'Papua Barat Daya', latitude: -1.19, longitude: 132.19, elevation: 200, monsoonZone: 2 },
]
